name: dl_papers
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - numpy
  - scipy
  - ipykernel
  - transformers
  - tqdm
  - docopt
  - nltk
  - torchvision
  - pip
  - pip:
    - sentencepiece
    - sacrebleu
    - tensorboard
